### ISSUE TITLE
Dead link: ordinalsconference.com

### ISSUE THREAD

**Issue by whoabuddy** [neu-fi/awesome-ordinals#12]
Just tried this out and can't get a response from the site:

https://ordinalsconference.com/

![image](https://user-images.githubusercontent.com/9038904/224122217-f2e47d11-ff08-4b7a-bcb1-421e5754f587.png)

I did find a link [to the Ordinals 2023 conference](https://ordinals2023.com/) here - is that the same thing? If not, should we add it?

**Comment by daggerhashimoto** [comment]
Looks like they've rebranded into https://ordinals2023.com/ 

Fixed by 706b502241acd31690158988032a042654a29074
