### ISSUE TITLE
Add missing resources from post

### ISSUE THREAD

**Issue by whoabuddy** [neu-fi/awesome-ordinals#6]
This [twitter post](https://twitter.com/adamamcbride/status/1626608046523940864) has a great summary of tooling, turns out their building a list as well:

https://github.com/crypt0biwan/ordinals/blob/main/README.md

**Comment by whoabuddy** [comment]
Some things I'll note while comparing the two:

- the level 2 headings make nice visual separators with the divider
- the categories are cleanly laid out and defined
- the links are exposed, which some people may like (I prefer the layout in #4)
- there are some links that we could add to #5 or in a separate PR

Should we review the layout/categories between the two lists and against the awesome-list standards mentioned in #1?

**Comment by hantuzun** [comment]
I reviewed your PRs (https://github.com/neu-fi/awesome-ordinals/pull/4 & https://github.com/neu-fi/awesome-ordinals/pull/5) and they were alright. Thank you a lot for your contributions.
